define([
    'utils/loader',
    './directives/remove',
    './directives/active_tab',
    './directives/alert',
    './directives/appmessages',
    './directives/readmore',
    './directives/datatables',
    './directives/media_type',
    './directives/timeago',
    './directives/dialog',
    './directives/form',
    './directives/input',
    './directives/validators/blacklist',
    './directives/validators/filechecker',
    './directives/dropdown',
    './directives/ng_esc',
    './directives/upload',
    './directives/checkbox_menu',
    './directives/checkbox_click',
    './directives/visibility_handler',
    './directives/appmenu',
    './directives/actions_menu',
    './directives/modelviewer',
    './directives/breadcrumb',
    './directives/player',
    './directives/delayed_search',
    './directives/bg_image',
    './directives/spinner',
    './directives/auth',
    './directives/appheader',
    './factories/dialog',
    './factories/rest',
    './factories/image',
    './factories/utils',
    './factories/player',
    './filters/disabled',
    './controllers/appmessages',
    './controllers/visibility',
    './controllers/datatables',
    './controllers/listcontroller',
    './controllers/model_editcontroller',
    './controllers/upload',
    './controllers/audioplayer',
    './controllers/videoplayer',
    './controllers/dropdown',
    './controllers/modelviewer',
    './services/appmessages',
    './services/network',
    './services/logger',
    './services/urlresolver',
    './services/user'
], function (ModuleLoader) {

    return new ModuleLoader({
        name: 'utils',
        dependencies: ['ngSanitize', 'ui.select', 'ui.bootstrap', 'ngFileUpload'],
        modules: Array.prototype.slice.call(arguments, 1)
    }).getModule();
});
